name: Tributech CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main, feature/*, hotfix/* ]

jobs:
  images:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: 'GitVersion.yml'
      - name: Calculate Browser Tags
        id: prep-browser
        run: |
          DOCKER_IMAGE=tributech.azurecr.io/iot-browser
          TAGS=""
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          TAGS="$TAGS,${DOCKER_IMAGE}:${{env.GitVersion_SemVer}}"
          echo "tags=${TAGS}" >> $GITHUB_ENV
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: tributech.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET  }}
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Build and push browser image image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.tags }}
          push: true